### ISSUE TITLE
Instalacion de Ubuntu, WSL, Rust

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/SistemadeVentas#1]
![Imagen1](https://github.com/user-attachments/assets/0649e99f-09d5-47ca-a990-d5c43c2a991f)
![Imagen2](https://github.com/user-attachments/assets/f05f9e1f-b5e4-428d-bac2-8e215ba1f4bf)
![Imagen3](https://github.com/user-attachments/assets/9456e71b-5714-4301-8dcb-236ad9c4e629)
![Imagen4](https://github.com/user-attachments/assets/abf89fe6-caa4-46eb-9ff2-8b094999222b)
Se instalan las herramientas necesarias para ocupar durante la ejecucion del contrato

**Comment by Arnold-Js** [comment]
closses
