### ISSUE TITLE
Implementar Contador

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/SistemadeVentas#15]

**Comment by Arnold-Js** [comment]
esta en progreso, ejecutando comandos para el contador

**Comment by AmilkarVladimiR** [comment]
Estamos verificando los comandos correctos para la creación de contratos inteligentes

**Comment by SANDRAVELASCO** [comment]
Se están implementando los comandos para verificar su funcionalidad, es decir que cumplan con lo de implementar el contador que vamos a usar

**Comment by SANDRAVELASCO** [comment]
Para comenzar con un nuevo proyecto en Soroban, utilizamos el comando "stellar contract init" para inicializar el directorio con uno de los contratos de ejemplo disponibles en el repositorio, soroban-examples.
En este caso, optamos por el contrato "increment".
Estando ubicados en el directorio "soroban-hola-mundo", ejecutamos el siguiente comando en la terminal: "stellar contract init ./ --with-example increment
": 
![Imagen1](https://github.com/user-attachments/assets/1a49ae49-9a0b-466b-b302-c4a534e639fc)

**Comment by SANDRAVELASCO** [comment]
Creación del directorio del contrato

Al ejecutar el comando anterior, se ha creado automáticamente un nuevo directorio dentro de la estructura del proyecto, ubicado en "contracts/increment". este directorio contiene el código y los archivos necesarios para el contrato de "increment":
![Imagen2](https://github.com/user-attachments/assets/73ee1fd1-bb0b-4ec7-9f82-b19df3cb88e3)

**Comment by SANDRAVELASCO** [comment]
Generación del archivo .wasm, se ejecuta el siguente comando en la terminal: "cargo build --release --target wasm32-unknown-unknown
", este comando compila el contrato en el perfil release, optimizando el código para su ejecución, el parámetro --target wasm32-unknown-unknown especifica que la compilacion debe generarse en el formato WebAssembly (Wasm), necesario para la ejecución del entorno de Soroban, como resultado genera un archivo .wasm en el directorio de compilación, listo para ser implementadoe en la red.

**Comment by SANDRAVELASCO** [comment]
Instalación del contrato en la red de Stellar
Para instalar el contrato en la red de prueba de Stellar, utilizamos el siguiente comando, que sube el archivo .wasm compilado a la red: "stellar contract install \
  --network testnet \
  --source raelCuenta \
  --wasm target/wasm32-unknown-unknown/release/soroban_increment_contract.wasm
"
Este comando especifica la red de prueba (--network testnet), la cuenta de origen para la instalación (--source raelCuenta) y la ubicación del archivo .wasm generado en el directorio de compilación. Es importante señalar que este comando no genera un ID de contrato, sino que simplemente sube el contrato a la red.
![Imagen4](https://github.com/user-attachments/assets/a9c998ba-453a-41c6-9d2e-9d43bed9c771)

**Comment by SANDRAVELASCO** [comment]
1. Actualizar Stellar Cli
Para poder implementar el contrato del contador, fué necesario actualizar Stellar-cli cpn el siguiente comando: cargo install --locked stellar-cli --features opt --force

**Comment by SANDRAVELASCO** [comment]
2. Actualizar Rust
En este caso fué necesario actualizar rust para tener compatibilidad con stellar-cli con el siguiente comando: **rustup update**

**Comment by SANDRAVELASCO** [comment]
3. Incorporación del contrato "Contador" al proyecto
En este paso se añade un contrato inteligente llamado "CONTADOR" a nuestro proyecto. Para ello, se utilizó el comando "stellar contract init", el cual nos permitió inicializar un nuevo proyecto con uno de los contratos predefinidos disponibles en el repositorio oficial de Soroban, esto se logra mediante la opcion --with-example o la version abreviada -w. 
Entonces desde el directorio principal del proyecto, se ejecutó el siguiente comando: 
stellar contract init ./ --with-example increment
Este comando inicializa el proyecto en el directorio actual (./) y añade el contrato de ejemplo "increment", deiseñado para implementar un contador . Durante este proceso, se crean automáticamente los archivos y la estructura necesaria, incluyendo el archivo Cargo.toml y las definiciones del contrato en la carpeta src/lib.rs. Esto nos permite comenzar a trabajar con el contrato de manera inmediata y utilizarlo como base para nuestras implementaciones personalizadas que se harán mas adelante: ![Image](https://github.com/user-attachments/assets/b9cef666-2ce6-4057-b6c2-964c9b302825) 
![Image](https://github.com/user-attachments/assets/b365747a-2712-488a-9054-d1410b0870a9)

**Comment by SANDRAVELASCO** [comment]
4. Construcción del contrato inteligente

Una vez que se añadió el contrato al proyecto, se procedió a compilarlo para generar el archivo ejecutable en formato WebAssembly (Wasm), que es el estándar utilizado por los contratos inteligentesen la red Soroban, para lograr este paso utilizamos el siguiente comando: cargo build --release --target wasm32-unknown-unknown
Acciones que siceden al momento de ejecuar el comando: 
1. Especifica el perfil de compilación: La opción --release indica que el contrato se compilará en modo de lanzamiento , lo cual optimiza el binario generado para su uso en producción, lo cual implica mejoras de rendimiento y reducción del tamaño del archivo. 
Al ejecutar el comando se compilan los contratos inteligentes definidos en el proyecto (en este caso increment y hello world), como resultado se genera un archivo .wasm optimizadoen la carpeta target/wasm32-unknown-unknown/release/, este archivo es el que posteriormente se implementará en la red blockchain: 
![Image](https://github.com/user-attachments/assets/9a6a0bce-f795-4980-ab13-ec1918726493)

**Comment by SANDRAVELASCO** [comment]
Paso 5. Subir los byes del contrato a la red Stellar
En este paso procedimos a instalar el contrato inteligente en la red Stellar. Para ello, subimos el archivo WASM generado anteriormente a la red especificada (en este caso, la red de prueba testnet) utilizando el comando stellar contract install, comando ejecutado: " stellar contract install \
  --network testnet \
  --source raelCuenta \
  --wasm target/wasm32-unknown-unknown/release/soroban_increment_contract.wasm
"
![Image](https://github.com/user-attachments/assets/9b90f425-7a65-40c6-886f-b982e63fad3e)
Este comando especifica la red de destino, define la cuenta fuente y carga el archivo wasm, en donde la opción --wasm apunta al archivo compilado soroban_increment_contract.wasm, ubicado en la carpeta de salida generada por el proceso de construcción.
En resumen al ejecutar este comando, el archivo WASM se sube a la red, y el sistema genera un ID único del contrato, el ID generado permite interactuar con el contrato y realizar operaciones posteriores, como invicar funciones o realizar pruebas. Ete paso es esencial para que el contrato quede registrado y disponible en la red Stellar, permitiendo su interacción en los siguientes pasos del desarrollo.

**Comment by SANDRAVELASCO** [comment]
6. Crear la instancia del contrato

En este paso, se crea una instancia del contrato en la red Stellar, esto asocia un nuevo ID de contrato con los bytes del contrato cargados previamente en el paso anterior, para realizar esta acción se hizo uso del siguiente comando: stellar contract deploy \
  --wasm-hash d76de1766e91abf3f716837a9479cfd2076c2261f7c4d37f1f2128a0064861b2 \
  --source raelCuenta \
  --network testnet
![Image](https://github.com/user-attachments/assets/f7a7f18f-2984-442b-b7ed-83da5ff45a9a)

El comando ejecutado realizó lo siguiente: 
1. Hash del contrato WASM: La opción --wasm-hashincluye el hash generado en el paso anterior (por ejemplo, d76de1766e91abf3f716837a9479cfd2076c2261f7c4d37f1f2128a0064861b2). Este hash identifica de manera única los bytes del contrato almacenados en la red Stellar y garantiza la integridad del código que será instanciado.
2. Cuenta fuente: Con --source raelCuenta, se utilizará la cuenta desde la cual se firmará y se desplegará la instancia del contrato. Esta cuenta debe estar configurada correctamente y contar con los permisos necesarios.
3. Red de destino: La opción --network testnetindica que el despliegue se realizará en la red de prueba de Stellar.

**Proceso del comando**

Simulación : El comando primero simula la transacción de despliegue para validar que todo esté correcto.
Envío de transacción : Luego envía la transacción de implementación a la red testnet de Stellar.
Confirmación : Una vez procesada la transacción, se genera un ID de contrato único que se puede utilizar para interactuar con el contrato.

**Comment by SANDRAVELASCO** [comment]
7. Invocación del contrato
Una vez implementado el contrato en la red de pruebas (testnet), se obtiene un identificador único (ID) necesario para interactuar con el contrato. 
Para invocar el contrato y ejecutar una de sus funciones, se utilizó el comando stellar contract invoke de la siguiente manera: 
**stellar contract invoke \
--id CAW54HH5KCJ5XKFHMNXJ5SFRVEC2UKXOE4KFOEXJ4AYNR4NDEOF3XMCJ \
--source raelCuenta \
--network testnet \
-- \
increment**

Este comando ejecuta la función increment del contrato, utilizando la cuenta proporcionada como fuente de la transacción en la red de pruebas. El resultado fué la transacción firmada, y el valor que es retornado después de la primera invocación, y sucesivamente al ejecutar nuevamente el comando, el contrato incrementa su valor, generando otra transacción firmada.
![Image](https://github.com/user-attachments/assets/d7bf99aa-0472-4ad0-937c-8c6e6ea3c0b9)
