### ISSUE TITLE
Instalacion de librerias para visual Rust-Analyzer y codellDB

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/SistemadeVentas#3]
![Imagen5](https://github.com/user-attachments/assets/092839fd-59bf-41ce-b464-69e70d8d6926)
![Imagen6](https://github.com/user-attachments/assets/384cbe24-f768-4e45-bb21-a409dd544207)
![Imagen7](https://github.com/user-attachments/assets/65eb02b4-fcfe-4dc9-9109-a5b031afb6f2)
![Imagen8](https://github.com/user-attachments/assets/2e1dc299-4a0d-4a35-861a-350d9cddc3e3)
Se instalan las librerias necesarias

**Comment by Arnold-Js** [comment]
Close issues #3
