### ISSUE TITLE
Creación de contrato inteligente

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/SistemadeVentas#4]
![Imagen9](https://github.com/user-attachments/assets/b4165136-0a0e-48ec-a6e0-559ed2513ee9)
![Imagen10](https://github.com/user-attachments/assets/5aba2ab1-451e-4149-b93e-799d52727910)
![Imagen11](https://github.com/user-attachments/assets/2c978791-3389-4d70-a7d1-1fc8b3937f0d)
![Imagen12](https://github.com/user-attachments/assets/7cc46652-4ce9-46b5-a6f5-d75e7c40fb27)
![Imagen13](https://github.com/user-attachments/assets/00dfd737-f00b-4770-b19b-c699e54ef095)

**Comment by Arnold-Js** [comment]
Close issues #4
