### ISSUE TITLE
Corrida del contrato inteligente

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/SistemadeVentas#5]
Mediante comandos se ejecutan los comandos para correr el contrato
![Imagen14](https://github.com/user-attachments/assets/945b784f-58c6-4558-a429-2c2f67fff025)
![Imagen15](https://github.com/user-attachments/assets/be87b99f-e5e2-4a56-b712-85b8a6e97438)
![Imagen16](https://github.com/user-attachments/assets/676a9cee-1f52-41b7-b9fd-0a1e4b18eb22)
![Imagen17](https://github.com/user-attachments/assets/3079669b-a5bc-464c-9e32-a6db4ad0d9ab)

**Comment by Arnold-Js** [comment]
Close issues  #5
